services:
  monorepo_container:
    container_name: monorepo_container
    build:
      context: ../application
      dockerfile: dockerfile
      args:
        - NODE_VERSION=22.1
      target: dev-runner
    restart: on-failure
    volumes:
      - "../application:/app"
    ports:
      - "3000:3000"
